functionsDirectory = "/Users/moayed/Desktop/Projects/careai-site/marketing-site/netlify/functions"
functionsDirectoryOrigin = "ui"
headersOrigin = "inline"
redirectsOrigin = "inline"

[images]
remote_images = ["^(?:https:\\/(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$"]

[functions]

[functions.emails]
included_files = ["./emails/**"]

[functions."*"]

[[plugins]]
origin = "default"
package = "@netlify/plugin-nextjs"

[plugins.inputs]

[[plugins]]
origin = "ui"
package = "@netlify/plugin-lighthouse"

[plugins.inputs]

[[plugins]]
origin = "ui"
package = "@netlify/plugin-emails"
pinned_version = "1"

[plugins.inputs]

[build]
publish = "/Users/moayed/Desktop/Projects/careai-site/marketing-site/out"
publishOrigin = "config"
commandOrigin = "config"
base = "/Users/moayed/Desktop/Projects/careai-site/marketing-site"
command = "npm run build"
functions = "/Users/moayed/Desktop/Projects/careai-site/marketing-site/netlify/functions"

[build.environment]
NODE_ENV = "production"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
X-Robots-Tag = "noindex, nofollow"
Cache-Control = "no-store, no-cache, must-revalidate"
Pragma = "no-cache"
Expires = "0"

[[headers]]
for = "/_next/static/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
from = "/*"
to = "https://app.careai.app/:splat"
status = 302.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/_next/image/"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200.0
force = false

[redirects.query]
url = ":url"
w = ":width"
q = ":quality"

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/_ipx/*"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200.0
force = false

[redirects.query]
url = ":url"
w = ":width"
q = ":quality"

[redirects.conditions]

[redirects.headers]