[build]
command = "npm run build"
publish = "out"

[build.environment]
NEXT_TELEMETRY_DISABLED = "1"
NODE_VERSION = "20"

# --------- STATIC ASSET PASSTHROUGHS (TOP, BEFORE ANY CATCH-ALL) ----------
[[redirects]]
from = "/_next/*"
to   = "/_next/:splat"
status = 200
force = true

[[redirects]]
from = "/icons/*"
to   = "/icons/:splat"
status = 200
force = true

[[redirects]]
from = "/images/*"
to   = "/images/:splat"
status = 200
force = true

[[redirects]]
from = "/robots.txt"
to   = "/robots.txt"
status = 200
force = true

[[redirects]]
from = "/sitemap.xml"
to   = "/sitemap.xml"
status = 200
force = true

# --------- LOCALE & ROOT ROUTING FOR STATIC EXPORT ------------------------
[[redirects]]
from = "/"
to   = "/en/"
status = 301
force = true

# Optional: guarantee trailing slashes to map to /en/index.html etc.
[[redirects]]
from = "/:locale"
to   = "/:locale/"
status = 301
force = true

# --------- SECURITY & CACHING -------------------------------------------
[[headers]]
for = "/_next/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/icons/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
Cache-Control = "no-store, no-cache, must-revalidate"