name: Child Guard
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
jobs:
  verify-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ensure no build artifacts are committed
        run: |
          test ! -d out || { echo "Found out/ in repo"; exit 1; }
          test ! -d .next || { echo "Found .next/ in repo"; exit 1; }
          test ! -d node_modules || { echo "Found node_modules/ in repo"; exit 1; }
      - name: Lint workflow files exist
        run: test -f .github/workflows/child-guard.yml
